# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1134, 642)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("gui/icons/music.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.database_item_list_widget = QtWidgets.QListWidget(self.centralwidget)
        self.database_item_list_widget.setMinimumSize(QtCore.QSize(200, 0))
        self.database_item_list_widget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.database_item_list_widget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.database_item_list_widget.setModelColumn(0)
        self.database_item_list_widget.setSelectionRectVisible(True)
        self.database_item_list_widget.setObjectName("database_item_list_widget")
        self.verticalLayout_6.addWidget(self.database_item_list_widget, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_10.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6.addLayout(self.verticalLayout_10)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.currently_text_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.currently_text_label.setFont(font)
        self.currently_text_label.setTextFormat(QtCore.Qt.AutoText)
        self.currently_text_label.setObjectName("currently_text_label")
        self.horizontalLayout_7.addWidget(self.currently_text_label, 0, QtCore.Qt.AlignLeft)
        self.currently_playing_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.currently_playing_label.setFont(font)
        self.currently_playing_label.setText("")
        self.currently_playing_label.setObjectName("currently_playing_label")
        self.horizontalLayout_7.addWidget(self.currently_playing_label)
        self.verticalLayout_12.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.music_position_slider = QtWidgets.QSlider(self.centralwidget)
        self.music_position_slider.setMaximumSize(QtCore.QSize(16777215, 10))
        self.music_position_slider.setStyleSheet("QSlider::groove:horizontal {\n"
"border: 1px solid #bbb;\n"
"background: white;\n"
"height: 4px;\n"
"border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"background: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #55f, stop: 1 #55f);\n"
"background: qlineargradient(x1: 0, y1: 0.2, x2: 1, y2: 1,\n"
"    stop: 0 #55f, stop: 1 #55f);\n"
"border: 1px solid #777;\n"
"height: 10px;\n"
"border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"background: #fff;\n"
"border: 1px solid #777;\n"
"height: 10px;\n"
"border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #eee, stop:1 #ccc);\n"
"border: 1px solid #777;\n"
"width: 15px;\n"
"margin-top: -3px;\n"
"margin-bottom: -3px;\n"
"border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #fff, stop:1 #ddd);\n"
"border: 1px solid #444;\n"
"border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"}")
        self.music_position_slider.setMaximum(0)
        self.music_position_slider.setPageStep(0)
        self.music_position_slider.setOrientation(QtCore.Qt.Horizontal)
        self.music_position_slider.setObjectName("music_position_slider")
        self.horizontalLayout_9.addWidget(self.music_position_slider)
        self.song_time_label = QtWidgets.QLabel(self.centralwidget)
        self.song_time_label.setMinimumSize(QtCore.QSize(75, 0))
        self.song_time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.song_time_label.setObjectName("song_time_label")
        self.horizontalLayout_9.addWidget(self.song_time_label)
        self.verticalLayout_12.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.open_temp_folder = QtWidgets.QToolButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("gui/icons/archive-folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_temp_folder.setIcon(icon1)
        self.open_temp_folder.setObjectName("open_temp_folder")
        self.horizontalLayout_8.addWidget(self.open_temp_folder)
        self.load_last_query_button = QtWidgets.QToolButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("gui/icons/replace.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.load_last_query_button.setIcon(icon2)
        self.load_last_query_button.setObjectName("load_last_query_button")
        self.horizontalLayout_8.addWidget(self.load_last_query_button)
        self.open_query_button = QtWidgets.QToolButton(self.centralwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("gui/icons/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_query_button.setIcon(icon3)
        self.open_query_button.setObjectName("open_query_button")
        self.horizontalLayout_8.addWidget(self.open_query_button)
        self.save_query_button = QtWidgets.QToolButton(self.centralwidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("gui/icons/save-as.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_query_button.setIcon(icon4)
        self.save_query_button.setObjectName("save_query_button")
        self.horizontalLayout_8.addWidget(self.save_query_button)
        self.search_query_button = QtWidgets.QToolButton(self.centralwidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("gui/icons/search2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_query_button.setIcon(icon5)
        self.search_query_button.setObjectName("search_query_button")
        self.horizontalLayout_8.addWidget(self.search_query_button)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.stop_button = QtWidgets.QToolButton(self.centralwidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("gui/icons/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop_button.setIcon(icon6)
        self.stop_button.setObjectName("stop_button")
        self.horizontalLayout_8.addWidget(self.stop_button)
        self.play_pause_button = QtWidgets.QToolButton(self.centralwidget)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("gui/icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play_pause_button.setIcon(icon7)
        self.play_pause_button.setObjectName("play_pause_button")
        self.horizontalLayout_8.addWidget(self.play_pause_button)
        self.record_query_button = QtWidgets.QToolButton(self.centralwidget)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("gui/icons/record.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap("gui/icons/recording.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon8.addPixmap(QtGui.QPixmap("gui/icons/recording.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.record_query_button.setIcon(icon8)
        self.record_query_button.setCheckable(True)
        self.record_query_button.setObjectName("record_query_button")
        self.horizontalLayout_8.addWidget(self.record_query_button)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.verticalLayout_12.addLayout(self.horizontalLayout_8)
        self.verticalLayout_11.addLayout(self.verticalLayout_12)
        self.verticalLayout.addLayout(self.verticalLayout_11)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label, 0, QtCore.Qt.AlignTop)
        self.result_table = QtWidgets.QTableWidget(self.centralwidget)
        self.result_table.setEnabled(True)
        self.result_table.setMinimumSize(QtCore.QSize(400, 200))
        self.result_table.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.result_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.result_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.result_table.setAutoScroll(False)
        self.result_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.result_table.setDragDropOverwriteMode(False)
        self.result_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.result_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.result_table.setTextElideMode(QtCore.Qt.ElideLeft)
        self.result_table.setShowGrid(False)
        self.result_table.setWordWrap(False)
        self.result_table.setCornerButtonEnabled(False)
        self.result_table.setObjectName("result_table")
        self.result_table.setColumnCount(5)
        self.result_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.result_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.result_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.result_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.result_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.result_table.setHorizontalHeaderItem(4, item)
        self.result_table.horizontalHeader().setVisible(True)
        self.result_table.horizontalHeader().setCascadingSectionResizes(False)
        self.result_table.horizontalHeader().setDefaultSectionSize(45)
        self.result_table.horizontalHeader().setHighlightSections(False)
        self.result_table.horizontalHeader().setMinimumSectionSize(20)
        self.result_table.horizontalHeader().setStretchLastSection(True)
        self.result_table.verticalHeader().setVisible(False)
        self.result_table.verticalHeader().setHighlightSections(False)
        self.verticalLayout_5.addWidget(self.result_table)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.midiViewer = PianoWidget(self.centralwidget)
        self.midiViewer.setObjectName("midiViewer")
        self.verticalLayout_3.addWidget(self.midiViewer, 0, QtCore.Qt.AlignVCenter)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.zoom_slider = QtWidgets.QSlider(self.centralwidget)
        self.zoom_slider.setMinimum(10)
        self.zoom_slider.setMaximum(200)
        self.zoom_slider.setSingleStep(1)
        self.zoom_slider.setProperty("value", 50)
        self.zoom_slider.setOrientation(QtCore.Qt.Horizontal)
        self.zoom_slider.setTickInterval(1)
        self.zoom_slider.setObjectName("zoom_slider")
        self.horizontalLayout_5.addWidget(self.zoom_slider)
        self.zoom_out_button = QtWidgets.QToolButton(self.centralwidget)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("gui/icons/zoom-out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoom_out_button.setIcon(icon9)
        self.zoom_out_button.setObjectName("zoom_out_button")
        self.horizontalLayout_5.addWidget(self.zoom_out_button)
        self.zoom_in_button = QtWidgets.QToolButton(self.centralwidget)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("gui/icons/zoom-in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoom_in_button.setIcon(icon10)
        self.zoom_in_button.setObjectName("zoom_in_button")
        self.horizontalLayout_5.addWidget(self.zoom_in_button)
        self.lock_view_button = QtWidgets.QToolButton(self.centralwidget)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("gui/icons/padlock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon11.addPixmap(QtGui.QPixmap("gui/icons/lock.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.lock_view_button.setIcon(icon11)
        self.lock_view_button.setCheckable(True)
        self.lock_view_button.setChecked(True)
        self.lock_view_button.setObjectName("lock_view_button")
        self.horizontalLayout_5.addWidget(self.lock_view_button)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1134, 21))
        self.menubar.setObjectName("menubar")
        self.menuData = QtWidgets.QMenu(self.menubar)
        self.menuData.setObjectName("menuData")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Database = QtWidgets.QAction(MainWindow)
        self.actionLoad_Database.setIcon(icon3)
        self.actionLoad_Database.setObjectName("actionLoad_Database")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.action_save_query = QtWidgets.QAction(MainWindow)
        self.action_save_query.setIcon(icon4)
        self.action_save_query.setObjectName("action_save_query")
        self.action_load_query = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("ui/music.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_load_query.setIcon(icon12)
        self.action_load_query.setObjectName("action_load_query")
        self.action_load_database = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("ui/database.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_load_database.setIcon(icon13)
        self.action_load_database.setObjectName("action_load_database")
        self.action_open_database = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("gui/icons/database.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_open_database.setIcon(icon14)
        self.action_open_database.setObjectName("action_open_database")
        self.action_open_query = QtWidgets.QAction(MainWindow)
        self.action_open_query.setIcon(icon3)
        self.action_open_query.setObjectName("action_open_query")
        self.action_Add_Folder_to_Database = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("gui/icons/database_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Add_Folder_to_Database.setIcon(icon15)
        self.action_Add_Folder_to_Database.setObjectName("action_Add_Folder_to_Database")
        self.menuData.addAction(self.action_open_database)
        self.menuData.addAction(self.action_Add_Folder_to_Database)
        self.menuData.addSeparator()
        self.menuData.addAction(self.action_open_query)
        self.menuData.addAction(self.action_save_query)
        self.menuData.addSeparator()
        self.menuData.addAction(self.actionExit)
        self.menubar.addAction(self.menuData.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Melody Query Tool"))
        self.label_2.setText(_translate("MainWindow", "Database items"))
        self.currently_text_label.setText(_translate("MainWindow", "Currently Selected:"))
        self.song_time_label.setText(_translate("MainWindow", " 0:00/ 0:00"))
        self.open_temp_folder.setToolTip(_translate("MainWindow", "Opens selection of previously recorded queries"))
        self.open_temp_folder.setText(_translate("MainWindow", "..."))
        self.load_last_query_button.setToolTip(_translate("MainWindow", "Load last query"))
        self.load_last_query_button.setText(_translate("MainWindow", "..."))
        self.open_query_button.setToolTip(_translate("MainWindow", "Open a query"))
        self.open_query_button.setText(_translate("MainWindow", "..."))
        self.save_query_button.setToolTip(_translate("MainWindow", "Save a recorded query"))
        self.save_query_button.setText(_translate("MainWindow", "..."))
        self.search_query_button.setToolTip(_translate("MainWindow", "Start a search for the selected query"))
        self.search_query_button.setText(_translate("MainWindow", "..."))
        self.stop_button.setText(_translate("MainWindow", "..."))
        self.play_pause_button.setText(_translate("MainWindow", "..."))
        self.record_query_button.setToolTip(_translate("MainWindow", "Record a new query"))
        self.record_query_button.setText(_translate("MainWindow", "..."))
        self.label.setText(_translate("MainWindow", "Query results"))
        item = self.result_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Rank"))
        item = self.result_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Score"))
        item = self.result_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "[%]"))
        item = self.result_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Match"))
        item = self.result_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Music Piece"))
        self.zoom_slider.setToolTip(_translate("MainWindow", "Zoom Slider"))
        self.zoom_out_button.setToolTip(_translate("MainWindow", "Zoom out"))
        self.zoom_out_button.setText(_translate("MainWindow", "..."))
        self.zoom_in_button.setToolTip(_translate("MainWindow", "Zoom in"))
        self.zoom_in_button.setText(_translate("MainWindow", "..."))
        self.lock_view_button.setToolTip(_translate("MainWindow", "Scroll Lock"))
        self.lock_view_button.setText(_translate("MainWindow", "..."))
        self.menuData.setTitle(_translate("MainWindow", "File"))
        self.actionLoad_Database.setText(_translate("MainWindow", "Load Database"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.action_save_query.setText(_translate("MainWindow", "Save Query..."))
        self.action_load_query.setText(_translate("MainWindow", "Query"))
        self.action_load_database.setText(_translate("MainWindow", "Database"))
        self.action_open_database.setText(_translate("MainWindow", "New Database..."))
        self.action_open_query.setText(_translate("MainWindow", "Open Query..."))
        self.action_Add_Folder_to_Database.setText(_translate("MainWindow", "Add Folder to Database..."))

from gui.piano_roll_editor import PianoWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

